server:
  port: 8083
  shutdown: graceful

spring:
  application:
    name: ai-memo

  profiles:
    default: dev

  lifecycle:
    timeout-per-shutdown-phase: 30s

  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DATABASE}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 3000

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
